import { User } from "@auth0/auth0-react";

export const data: User[] = [
  { id: 1, name: "John Doe", email: "john@example.com", role: "Admin" },
  { id: 2, name: "Jane Smith", email: "jane@example.com", role: "User" },
  {
    id: 3,
    name: "Michael Johnson",
    email: "michael@example.com",
    role: "User",
  },
  { id: 4, name: "Sarah Williams", email: "sarah@example.com", role: "Admin" },
  { id: 5, name: "James Brown", email: "james@example.com", role: "User" },
  { id: 6, name: "Emily Davis", email: "emily@example.com", role: "User" },
  { id: 7, name: "Robert Wilson", email: "robert@example.com", role: "Admin" },
  { id: 8, name: "Lisa Anderson", email: "lisa@example.com", role: "User" },
  { id: 9, name: "David Taylor", email: "david@example.com", role: "User" },
  {
    id: 10,
    name: "Jennifer Martinez",
    email: "jennifer@example.com",
    role: "Admin",
  },
  { id: 11, name: "Daniel Thomas", email: "daniel@example.com", role: "User" },
  {
    id: 12,
    name: "Jessica Garcia",
    email: "jessica@example.com",
    role: "User",
  },
  {
    id: 13,
    name: "Christopher Lee",
    email: "chris@example.com",
    role: "Admin",
  },
  {
    id: 14,
    name: "Michelle Rodriguez",
    email: "michelle@example.com",
    role: "User",
  },
  { id: 15, name: "Kevin White", email: "kevin@example.com", role: "User" },
  { id: 16, name: "Amanda Clark", email: "amanda@example.com", role: "Admin" },
  { id: 17, name: "Steven Hall", email: "steven@example.com", role: "User" },
  { id: 18, name: "Laura Lewis", email: "laura@example.com", role: "User" },
  { id: 19, name: "Joseph Young", email: "joseph@example.com", role: "Admin" },
  { id: 20, name: "Rachel King", email: "rachel@example.com", role: "User" },
  { id: 21, name: "Thomas Scott", email: "thomas@example.com", role: "User" },
  { id: 22, name: "Sandra Adams", email: "sandra@example.com", role: "Admin" },
  { id: 23, name: "Paul Baker", email: "paul@example.com", role: "User" },
  { id: 24, name: "Betty Nelson", email: "betty@example.com", role: "User" },
  { id: 25, name: "Mark Hill", email: "mark@example.com", role: "Admin" },
  { id: 26, name: "Carol Green", email: "carol@example.com", role: "User" },
  { id: 27, name: "George Evans", email: "george@example.com", role: "User" },
  { id: 28, name: "Ruth Turner", email: "ruth@example.com", role: "Admin" },
  {
    id: 29,
    name: "Edward Phillips",
    email: "edward@example.com",
    role: "User",
  },
  { id: 30, name: "Nancy Morris", email: "nancy@example.com", role: "User" },
  { id: 31, name: "Jason Carter", email: "jason@example.com", role: "Admin" },
  { id: 32, name: "Helen Rogers", email: "helen@example.com", role: "User" },
  { id: 33, name: "Frank Reed", email: "frank@example.com", role: "User" },
  { id: 34, name: "Donna Cook", email: "donna@example.com", role: "Admin" },
  { id: 35, name: "Jerry Morgan", email: "jerry@example.com", role: "User" },
  { id: 36, name: "Judy Bell", email: "judy@example.com", role: "User" },
  { id: 37, name: "Philip Murphy", email: "philip@example.com", role: "Admin" },
  { id: 38, name: "Gloria Cooper", email: "gloria@example.com", role: "User" },
  {
    id: 39,
    name: "Harry Richardson",
    email: "harry@example.com",
    role: "User",
  },
  { id: 40, name: "Teresa Cox", email: "teresa@example.com", role: "Admin" },
  { id: 41, name: "Bruce Howard", email: "bruce@example.com", role: "User" },
  { id: 42, name: "Louise Ward", email: "louise@example.com", role: "User" },
  { id: 43, name: "Ralph Torres", email: "ralph@example.com", role: "Admin" },
  { id: 44, name: "Joyce Peterson", email: "joyce@example.com", role: "User" },
  { id: 45, name: "Eugene Gray", email: "eugene@example.com", role: "User" },
  { id: 46, name: "Alice Brooks", email: "alice@example.com", role: "Admin" },
  { id: 47, name: "Peter Price", email: "peter@example.com", role: "User" },
  { id: 48, name: "Diane Watson", email: "diane@example.com", role: "User" },
  { id: 49, name: "Roger Sanders", email: "roger@example.com", role: "Admin" },
  { id: 50, name: "Marie Bennett", email: "marie@example.com", role: "User" },
  { id: 51, name: "Roy Wood", email: "roy@example.com", role: "User" },
  { id: 52, name: "Lois Barnes", email: "lois@example.com", role: "Admin" },
  { id: 53, name: "Johnny Ross", email: "johnny@example.com", role: "User" },
  { id: 54, name: "Jean Henderson", email: "jean@example.com", role: "User" },
  { id: 55, name: "Randy Coleman", email: "randy@example.com", role: "Admin" },
  { id: 56, name: "Cheryl Jenkins", email: "cheryl@example.com", role: "User" },
  { id: 57, name: "Carlos Perry", email: "carlos@example.com", role: "User" },
  { id: 58, name: "Joan Long", email: "joan@example.com", role: "Admin" },
  {
    id: 59,
    name: "Russell Patterson",
    email: "russell@example.com",
    role: "User",
  },
  {
    id: 60,
    name: "Catherine Hughes",
    email: "catherine@example.com",
    role: "User",
  },
  { id: 61, name: "Howard Foster", email: "howard@example.com", role: "Admin" },
  {
    id: 62,
    name: "Kathy Washington",
    email: "kathy@example.com",
    role: "User",
  },
  { id: 63, name: "Earl Butler", email: "earl@example.com", role: "User" },
  {
    id: 64,
    name: "Janice Simmons",
    email: "janice@example.com",
    role: "Admin",
  },
  { id: 65, name: "Albert Bryant", email: "albert@example.com", role: "User" },
  { id: 66, name: "Ruby Russell", email: "ruby@example.com", role: "User" },
  { id: 67, name: "Wayne Griffin", email: "wayne@example.com", role: "Admin" },
  { id: 68, name: "Phyllis Diaz", email: "phyllis@example.com", role: "User" },
  { id: 69, name: "Randy Hayes", email: "randy.h@example.com", role: "User" },
  { id: 70, name: "Bonnie Myers", email: "bonnie@example.com", role: "Admin" },
];
